language: go

go:
  - "1.12"
  - "1.13"

branches:
  only:
    - master
    - /^version-.*$/

env:
  global:
    - GO111MODULE=on

matrix:
  include:
    - os: linux
      env: TEST_ARGS="-tags=integration"
    - os: osx

cache:
    directories:
      - vendor

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./cc-test-reporter; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./cc-test-reporter before-build; fi

install:
  - make deps

script:
  - make test

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

deploy:
  - provider: script
    script: GORELEASER='curl -sL https://git.io/goreleaser | bash -s --' make release
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
